rss: atom.xml
fancybox: true
favicon: favicon.ico
inverse_sort: false  # Whether to sort all notes inversely
fold: true  # Whether to fold all the notebooks initially
scratch_name: Uncategorized  # Notebook name of posts without categories variables
google_analytics:
search:
  path: search.xml
  field: all
